In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

In [2]:
w=pd.read_csv("wine.csv")
w.head()

Alcohol  Malic_Acid   Ash  Ash_Alcanity  Magnesium  Total_Phenols  \
0    14.23        1.71  2.43          15.6        127           2.80   
1    13.20        1.78  2.14          11.2        100           2.65   
2    13.16        2.36  2.67          18.6        101           2.80   
3    14.37        1.95  2.50          16.8        113           3.85   
4    13.24        2.59  2.87          21.0        118           2.80   

   Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  Color_Intensity   Hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   OD280  Proline  Customer_Segment  
0   3.92     1065                 1  
1   3.40     1050                 1  
2   3.17     1185                 1  
3   3.45     1480                 1  
4   2.93      735                 1

In [3]:
w.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Alcohol               178 non-null    float64
 1   Malic_Acid            178 non-null    float64
 2   Ash                   178 non-null    float64
 3   Ash_Alcanity          178 non-null    float64
 4   Magnesium             178 non-null    int64  
 5   Total_Phenols         178 non-null    float64
 6   Flavanoids            178 non-null    float64
 7   Nonflavanoid_Phenols  178 non-null    float64
 8   Proanthocyanins       178 non-null    float64
 9   Color_Intensity       178 non-null    float64
 10  Hue                   178 non-null    float64
 11  OD280                 178 non-null    float64
 12  Proline               178 non-null    int64  
 13  Customer_Segment      178 non-null    int64  
dtypes: float64(11), int64(3)
memory usage: 19.6 KB


In [4]:
w.describe()

Alcohol  Malic_Acid         Ash  Ash_Alcanity   Magnesium  \
count  178.000000  178.000000  178.000000    178.000000  178.000000   
mean    13.000618    2.336348    2.366517     19.494944   99.741573   
std      0.811827    1.117146    0.274344      3.339564   14.282484   
min     11.030000    0.740000    1.360000     10.600000   70.000000   
25%     12.362500    1.602500    2.210000     17.200000   88.000000   
50%     13.050000    1.865000    2.360000     19.500000   98.000000   
75%     13.677500    3.082500    2.557500     21.500000  107.000000   
max     14.830000    5.800000    3.230000     30.000000  162.000000   

       Total_Phenols  Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  \
count     178.000000  178.000000            178.000000       178.000000   
mean        2.295112    2.029270              0.361854         1.590899   
std         0.625851    0.998859              0.124453         0.572359   
min         0.980000    0.340000              0.130000         0.410000   
25%         1.742500    1.205000              0.270000         1.250000   
50%         2.355000    2.135000              0.340000         1.555000   
75%         2.800000    2.875000              0.437500         1.950000   
max         3.880000    5.080000              0.660000         3.580000   

       Color_Intensity         Hue       OD280      Proline  Customer_Segment  
count       178.000000  178.000000  178.000000   178.000000        178.000000  
mean          5.058090    0.957449    2.611685   746.893258          1.938202  
std           2.318286    0.228572    0.709990   314.907474          0.775035  
min           1.280000    0.480000    1.270000   278.000000          1.000000  
25%           3.220000    0.782500    1.937500   500.500000          1.000000  
50%           4.690000    0.965000    2.780000   673.500000          2.000000  
75%           6.200000    1.120000    3.170000   985.000000          3.000000  
max          13.000000    1.710000    4.000000  1680.000000          3.000000

In [5]:
x=w.iloc[:,:-1]
print(x)
y=w.iloc[:,-1]
print(y)

     Alcohol  Malic_Acid   Ash  Ash_Alcanity  Magnesium  Total_Phenols  \
0      14.23        1.71  2.43          15.6        127           2.80   
1      13.20        1.78  2.14          11.2        100           2.65   
2      13.16        2.36  2.67          18.6        101           2.80   
3      14.37        1.95  2.50          16.8        113           3.85   
4      13.24        2.59  2.87          21.0        118           2.80   
..       ...         ...   ...           ...        ...            ...   
173    13.71        5.65  2.45          20.5         95           1.68   
174    13.40        3.91  2.48          23.0        102           1.80   
175    13.27        4.28  2.26          20.0        120           1.59   
176    13.17        2.59  2.37          20.0        120           1.65   
177    14.13        4.10  2.74          24.5         96           2.05   

     Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  Color_Intensity   Hue  \
0          3.06               

In [69]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.3,random_state=7)

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

In [70]:
def mymodel(mod):
    mod.fit(xtrain,ytrain)
    ypred=mod.predict(xtest)
    
    train=mod.score(xtrain,ytrain)
    test=mod.score(xtest,ytest)
    
    print(f"training accuracy: {train}\ntesting accuracy: {test}\n\n")
    print(classification_report(ytest,ypred))
    return mod

In [71]:
ler=mymodel(LogisticRegression())

training accuracy: 0.9516129032258065
testing accuracy: 0.9259259259259259


              precision    recall  f1-score   support

           1       0.80      0.92      0.86        13
           2       0.95      0.88      0.91        24
           3       1.00      1.00      1.00        17

    accuracy                           0.93        54
   macro avg       0.92      0.93      0.92        54
weighted avg       0.93      0.93      0.93        54



In [72]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
xtrain=sc.fit_transform(xtrain)
xtest=sc.fit_transform(xtest)

In [73]:
from sklearn.decomposition import PCA
pca=PCA(n_components=2)
xtrain=pca.fit_transform(xtrain)

In [74]:
pca.explained_variance_ratio_

array([0.37883117, 0.19313477])

In [75]:
xtrain

array([[-1.81517337, -1.6123072 ],
       [-1.453005  , -1.62732683],
       [-1.83957745, -1.12292748],
       [ 2.86783019,  1.21653656],
       [-2.34039558,  0.61777652],
       [ 2.74917025,  0.71994722],
       [-1.95055685,  2.97440193],
       [ 1.89696418, -1.65686143],
       [-2.33059639,  2.14579282],
       [ 2.5937783 ,  0.43552507],
       [-0.50750464,  3.97601685],
       [-0.38931048, -1.85354669],
       [-0.18674644, -1.67919932],
       [-0.90401779, -2.01214036],
       [ 1.67908073,  0.20820545],
       [ 0.23356735, -3.54758354],
       [ 0.58233055, -0.02003123],
       [ 3.54384148,  0.96402174],
       [-3.3285353 ,  2.43145508],
       [ 2.17559744,  0.98752487],
       [-2.59923054,  2.38077994],
       [-0.85755569, -1.77800676],
       [-1.7262637 , -0.88211225],
       [-2.5402201 ,  2.50079698],
       [-1.84243429, -1.61440552],
       [ 2.49485701,  0.21408643],
       [ 0.50403144, -1.46602269],
       [ 0.18232759, -0.83522998],
       [ 0.03136869,

In [76]:
xtest=pca.transform(xtest)
xtest

array([[-3.26001665e+00,  1.90025567e+00],
       [ 1.68865609e+00,  5.77409497e-01],
       [-2.57226495e+00,  1.54686121e+00],
       [-3.41812295e+00,  1.15884271e+00],
       [-2.74364735e-04, -9.10303145e-01],
       [-1.96318854e+00,  7.04614762e-01],
       [-1.84369516e-01, -8.04268439e-01],
       [ 1.79866655e+00, -1.11059615e-01],
       [ 7.25561356e-01, -1.06926007e+00],
       [-2.20367150e+00,  9.27662221e-01],
       [ 2.79027182e+00, -4.21344882e-01],
       [-1.22402397e-01, -3.45721103e+00],
       [-1.98474983e+00,  1.46819963e+00],
       [-7.67530779e-01, -1.92904906e+00],
       [ 6.05372387e-01, -2.08657793e+00],
       [-4.24369520e-01, -1.65511768e+00],
       [ 1.50921769e+00, -1.09142795e+00],
       [-1.09539455e+00,  2.88630439e+00],
       [ 3.22774183e+00,  4.83550033e-01],
       [ 1.68986602e+00,  1.69172016e+00],
       [ 1.88867248e+00, -1.27622476e+00],
       [ 2.23659522e+00, -2.29808965e+00],
       [-1.26012727e+00,  2.65312929e-01],
       [-5.

In [77]:
ler=mymodel(LogisticRegression())

training accuracy: 0.9516129032258065
testing accuracy: 0.9629629629629629


              precision    recall  f1-score   support

           1       0.93      1.00      0.96        13
           2       0.96      0.96      0.96        24
           3       1.00      0.94      0.97        17

    accuracy                           0.96        54
   macro avg       0.96      0.97      0.96        54
weighted avg       0.96      0.96      0.96        54

